Readme Updated
ArasLabs/innovator-client-example pull request #2
Opened 2019-03-22 19:06 UTC by sampoearas

Install Steps updated. Tested on 11.0 SP12, 15

2019-03-22 20:15 UTC, EliJDonahue requested changes
The usage steps look good. Just need to tweak the two release comments.

>Edit: typo

2019-03-22 20:15 UTC, EliJDonahue commented on README.md
> +[v1.0.1](https://github.com/ArasLabs/innovator-client-example/releases/tag/v1.0.1) | Updated Install steps
```suggestion
[v1.0.1](https://github.com/ArasLabs/innovator-client-example/releases/tag/v1.0.1) | Updated Install steps. Tested on 11.0 SP15, SP12.
```

2019-03-22 20:15 UTC, EliJDonahue commented on README.md
> +[v1.0.1](https://github.com/ArasLabs/innovator-client-example/releases/tag/v1.0.1) | Tested on 11.0 SP15, SP12
This project still supports 10.0 SPx and 11.0 SPx. You can include the tested versions in the release notes above.
```suggestion
[v1.0.1](https://github.com/ArasLabs/innovator-client-example/releases/tag/v1.0.1) | 10.0 SPx, 11.0 SPx
```

2019-03-22 20:54 UTC, sampoearas reviewed
Suggestions committed.

2019-03-23 02:01 UTC, EliJDonahue approved these changes

2019-03-23 02:01 UTC, merged